# github action workflow yml file
# 액션의 이름이다.
name: CI

# 언제 액션이 이루어질 지 정할 수 있다. 아래에 브랜치를 지정해주면 된다.
# 우리는 deploy 브랜치에 Push되면 자동 배포하도록 정의할 것이다.
on:
  push:
    branches: [ deploy ]

# 아래의 Job들이 깃헙 액션에서 진행된다.
jobs:
  # 하나의 Job을 정의한다. 여기서 Job의 이름은 build이다.
  deploy:
    name: DEPLOY
      # 빌드가 어느 운영체제에서 돌아가느냐?
    runs-on: ubuntu-18.04
    env:
      working-directory: ./BE

      # step은 job의 하위 집합이다. step에서 정의한 작업을 순차적으로 진행한다.
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
        
        # 위에서 정의한 브랜치로 체크아웃한다.
      - name: Checkout
        uses: actions/checkout@v2

        # 메시지를 출력한다.
      - name: Run a one-line script
        run: echo Start Deploy.
          
        # 자바 버전을 설정해준다.
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Gradle에 실행 권한을 부여한다.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
